### ISSUE TITLE
v1.0.0 release

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#151]
as we move towards the v1.0.0 release here are some outstanding TODOs:

- [x] tests (#143 )
- [x] no longer export `glm_forecast()` and `glm_quibble()` ? (#152 )
- [x] what to do about ILI nowcast with ILI Nearby being down ? (https://github.com/signaturescience/fiphde/issues/124)
- [x] fix "fallback" argument in `state_replace_ili_nowcast_all()` (https://github.com/signaturescience/fiphde/issues/159)
- [x] look into why `get_cdc_hosp()` only pulls data through 2020 (https://github.com/signaturescience/fiphde/issues/154)
- [x] get rid of the "remove_null_models" argument from `ts_fit_forecast()` (#156 )
- [x] address strict naming of model list in `ts_fit_forecast()` (#157 )
- [x] take out covariates from `ts_fit_forecast()` ? (https://github.com/signaturescience/fiphde/issues/158)
- [x] add examples and/or vignette for `fiphde_launcher()` (#153 )
- [x] organize example submission data (in `inst/extdata` ?) needed for `fiphde_launcher()` demonstration (#153)
- [x] drop `weighted_interval_score()` and `score_func_param_checker()` ? (see https://github.com/signaturescience/fiphde/issues/155)
- [x] plot categorical function as package function #160 
- [x] final check of built pkgdown site for typos, formatting, etc
- [x] final check that all examples are thorough and run successfully
- [x] final check on completeness of vignette(s)
- [x] *thoroughly* update NEWS.md with all of the changes
- [x] cut Github release once pulled to main

**Comment by vpnagraj** [comment]
@stephenturner im organizing some tasks for us to move forward with v1.0.0 release

hold on taking any action on the above until you and i talk a bit more ...

**Comment by vpnagraj** [comment]
also FYI that (after we talk through the list above a bit to make sure we're on the same page) ... we can dive into technical work and *submit PRs to [the new `v1.0.0` branch](https://github.com/signaturescience/fiphde/tree/v1.0.0)* (not `main`)

**Comment by vpnagraj** [comment]
@stephenturner im done adding individual issues (for now). again, lets hold off on taking any action until we can catch up

**Comment by stephenturner** [comment]
The vignette is good! Notable changes already made in 58de1034361ef8adfa1ea1ac5f331df586864019 and 2e8a6d9aafbbbb8f35947df46bafe99ae3641000

**Comment by stephenturner** [comment]
I just ran through the code interactively rather than loading from the precooked `vd` object, and everything works as written.
