### ISSUE TITLE
v2.1.0 release

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#222]
we're starting to work on new features and updates to internals for package ahead of the 2024-25 season.

we should prepare a minor release for v2.1.0

- [x] add extended time series data (#219)
- [x] add dataset with estimated unreported 2024 weeks (#220)
- [x] update categorical rate trend methods and data (#221)
- [x] include options for RESP-NET retrieval for Flusurv hospitalizations (#214)
- [x] fix bug in Fluview Flusurv hospitalization retrieval (#215)
- [x] add functionality to retrieve updated NHSN data stream (#225)
- [x] curate static retrospective hospitalization dataset (#227)
- [x] review all documentation (including spellcheck)
- [x] add v2.1.0 release notes to changelog
- [x] R CMD check
- [x] cut github release
