### ISSUE TITLE
initial forecast submission

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#60]
the first FluSight submission is due by 2022-01-10 at 11PM ET.

after discussion with @stephenturner it sounds like our primary modeling approach will be the GLM model selection framework. we have a working implementation to generate a submission-ready file:

https://github.com/signaturescience/fiphde/blob/main/scratch/initial-submission-glm.R

https://github.com/signaturescience/fiphde/blob/main/submission/SigSci-CREG/2021-12-30-SigSci-CREG.csv

we should try running this forecasting pipeline again next week to make sure we dont hit any snags ahead of the initial deadline. 

additionally we should aim to address the following before the first submission:

- [x] finish metadata file (see #16 )
- [x] finish GLM *and* TS-based submission formatting (see #10 )
- [x] include ILI nowcasting (see #43 )
- [x] incorporate generic data prep helper into submission script
- [x] resolve redundancy in state / national level GLM submission prep code
- [x] #77
- [x] if possible put together at least one TS-based submission as a secondary forecast
- [x] validation (#12 )
